ckrack_optimus:

    # Large prime number lower than 2147483647
    prime: "%env(int:OPTIMUS_PRIME)%"

    # The inverse prime so that (PRIME * INVERSE) & MAXID == 1
    inverse: "%env(int:OPTIMUS_INVERSE)%"

    # A large random integer lower than 2147483647
    random: "%env(int:OPTIMUS_RANDOM)%"

    # if set to true, param converter will continue with the next available param converters
    passthrough: true
